apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-docker-k8s-demo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-docker-k8s-demo
  template:
    metadata:
      labels:
        app: nodejs-docker-k8s-demo
    spec:
      containers:
        - name: nodejs-docker-k8s-demo
          image: amad101588/nodejs-docker-k8s-demo:latest
          envFrom:
            - configMapRef:
                name: nodejs-docker-k8s-demo