apiVersion: v1
kind: Service
metadata:
  name: nodejs-docker-k8s-demo
  namespace: dev
spec:
  selector:
    app: nodejs-docker-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
  type: NodePort

